### PR TITLE
Large Files Fix for Ventricular Bundle

### LINKED ISSUE #51: Downloading TorchScript file for ventricular_short_axis_3label produced NumPy file.
I was trying to download and see what the model.ts file is like for the [ventricular_short_axis_3label](https://github.com/Project-MONAI/model-zoo/blob/dev/models/ventricular_short_axis_3label/large_files.yml).

I used `gdown"https://drive.google.com/uc?id=158RMzaGtgMgY1hCneDXmqCx7u046RbZE"`, but got a NumPy file `SC-N-2-3-0.npy`

BTW, `gdown` with the URL for the model.pt file did get the `model.pt` file.

### PR DESCRIPTION
**Pull request by ericspod**
Signed-off-by: Eric Kerfoot <eric.kerfoot@kcl.ac.uk>

Fixes #51.

### Description
Tweak to the downloaded files to fix reference and add Torchscript version. The third file is the example data for the included notebook.

### Status
**Ready**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json`.
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
Hi @ericspod , it seems the torch version mentioned in `metadata` is wrong (https://github.com/Project-MONAI/model-zoo/runs/7413185027?check_suite_focus=true#step:2:256)

**Comment by ericspod** [comment]
> Hi @ericspod , it seems the torch version mentioned in `metadata` is wrong (https://github.com/Project-MONAI/model-zoo/runs/7413185027?check_suite_focus=true#step:2:256)

I'm not able to duplicate the issue locally. I have created an environment with Python3.8 and the stated versions of libraries, I can load the Torchscript model, create a fresh instance of the network and load weights into it, and save that fresh object to a Torchscript file. I also called `ckpt_export` directly in code and was able to successfully save and reload a Torchscript object. From the traceback that appeared to be what was attempted, though the complaint at the end is about internal Pytorch code which doesn't make much sense.

**Comment by yiheng-wang-nv** [comment]
> > Hi @ericspod , it seems the torch version mentioned in `metadata` is wrong (https://github.com/Project-MONAI/model-zoo/runs/7413185027?check_suite_focus=true#step:2:256)
> 
> I'm not able to duplicate the issue locally. I have created an environment with Python3.8 and the stated versions of libraries, I can load the Torchscript model, create a fresh instance of the network and load weights into it, and save that fresh object to a Torchscript file. I also called `ckpt_export` directly in code and was able to successfully save and reload a Torchscript object. From the traceback that appeared to be what was attempted, though the complaint at the end is about internal Pytorch code which doesn't make much sense.

Hi @ericspod , thanks for the clarification. I manually checked the issue, and your bundle is correct. There might be sth wrong with the test function, I will fix it soon.

**Comment by ericspod** [comment]
Hi @yiheng-wang-nv your fix has sorted the issue we were seeing, thanks!

**Review by yiheng-wang-nv — APPROVED** [review]

**Pull request merged**
