### PR TITLE
init blossom ci

### PR DESCRIPTION
**Pull request by YanxuanLiu**
Init Blossom CICD workflow

### CODE REVIEW

**Review by pxLi — APPROVED** [review]
LGTM. Please trigger some dummy PR builds after merged, thx~

**Comment by Nic-Ma** [comment]
Hi @wyli @yiheng-wang-nv ,

Could you please help review this PR? I think you have much experience on the Github workflow and Blossom.

Thanks in advance.

**Comment by pxLi** [comment]
> Hi @wyli @yiheng-wang-nv ,
> 
> Could you please help review this PR? I think you have much experience on the Github workflow and Blossom.
> 
> Thanks in advance.

this is the template from blossom, we can only modify the allowed users part. (blossom will do integrity check for all other parts, it will fail the check if we modified anything else). Just make sure the github IDs are correct, and we should be good~

**Review by yiheng-wang-nv — APPROVED** [review]

**Review by yiheng-wang-nv — APPROVED** [review]

**Pull request merged**
