### PR TITLE
Valve Landmark Bundle: Update to fix changes to EnsureChannelFirstd and further documentation

### PR DESCRIPTION
**Pull request by ericspod**
### Description
This fixes a discovered issue with the way transforms are used and adds a little more clarification to the documentation.

### Status
**Work in progress**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [x] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [x] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [x] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [x] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [x] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [x] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
CI test failed because of the numpy version. I checked th numpy 1.26 requirements and it needs to run with Python >= 3.9 but now we use python 3.8
Hi @ericspod , do you think if we can use an elder numpy version for this bundle so far? It seems MONAI supported python versions is 3.8+ (https://raw.githubusercontent.com/Project-MONAI/MONAI/dev/docs/images/python.svg)

If numpy 1.26 is necessary, it may need @YanxuanLiu 's help to modify the python used for blossom CI and then we can rerun the test for this PR.

**Comment by ericspod** [comment]
Any version of Numpy that's recent should be fine actually so I've changed it to be 1.25.2.

**Review by yiheng-wang-nv — APPROVED** [review]

**Pull request merged**
