### PR TITLE
modify python version for weekly test [skip-ci]

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes # .

### Description
This PR is used to update the weekly cpu test python version. `valve_landmarks` bundle now requires python 3.9+ to use numpy 1.25.2
https://github.com/Project-MONAI/model-zoo/pull/542/files#diff-a11099ce2eebc4ce9f0721ca6674516e415d68d306ad76f1574fa0985973ff79R16
I temporarily modify yaml file to trigger the weekly test on this PR and proves that the change works and will not impact other bundles.

https://github.com/Project-MONAI/model-zoo/actions/runs/7650854728

### Status
**Ready**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [ ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ ] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Review by KumoLiu — APPROVED** [review]

**Comment by yiheng-wang-nv** [comment]
will have some other trials here to figure why same python 3.8 setting works in premerge cpu test yaml file in:
https://github.com/Project-MONAI/model-zoo/actions/runs/7638316721/job/20843732588

cc @YanxuanLiu

**Comment by yiheng-wang-nv** [comment]
found the root cause why in premerge cpu test, although we specified python 3.8, a bundle that requires python 3.9 works:

`rm -rf /opt/hostedtoolcache` this line seems remove the prepared python 3.8
https://github.com/Project-MONAI/model-zoo/pull/550/commits/f5f80e99fa1d9413fa9ba08838546ecf8a24c6ce#diff-e86b0d56af46cea339db685fd25f72b174c3e2d07439a0c9a3f5315f1ec2d1a8R33

If having this line, it seems the system default python 3.10 works, thus CI can pass, like: https://github.com/Project-MONAI/model-zoo/actions/runs/7651709230
Without this line, CI failed, like: https://github.com/Project-MONAI/model-zoo/actions/runs/7651976256

cc @YanxuanLiu @KumoLiu

**Comment by yiheng-wang-nv** [comment]
> found the root cause why in premerge cpu test, although we specified python 3.8, a bundle that requires python 3.9 works:
> 
> `rm -rf /opt/hostedtoolcache` this line seems remove the prepared python 3.8 [f5f80e9#diff-e86b0d56af46cea339db685fd25f72b174c3e2d07439a0c9a3f5315f1ec2d1a8R33](https://github.com/Project-MONAI/model-zoo/commit/f5f80e99fa1d9413fa9ba08838546ecf8a24c6ce#diff-e86b0d56af46cea339db685fd25f72b174c3e2d07439a0c9a3f5315f1ec2d1a8R33)
> 
> If having this line, it seems the system default python 3.10 works, thus CI can pass, like: https://github.com/Project-MONAI/model-zoo/actions/runs/7651709230 Without this line, CI failed, like: https://github.com/Project-MONAI/model-zoo/actions/runs/7651976256
> 
> cc @YanxuanLiu @KumoLiu

according to the above finding, @KumoLiu and I found an issue of MONAI core CI, where some places also use `rm -rf /opt/hostedtoolcache` in the github ci to save the resources used. It may lead to:
the actual python env used to test is not what is set in the yml file. cc @wyli 
Let me create a ticket in MONAI core and describe more details.

**Pull request merged**
