### PR TITLE
431 update ldm bundles

### LINKED ISSUE #431: Use `pip install` for 2d and 3d ldm bundles
The lib is in: https://pypi.org/project/monai-generative/
and we do not need to install it by other ways.

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes #431 .

### Description
This PR is used to modify the dependency installed way of ldm bundles.

### Status
**Ready/Work in progress/Hold**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [ ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ ] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
The ci test is broken according to the issue that multiple versions of MONAI is installed:
https://github.com/Project-MONAI/model-zoo/actions/runs/5010337856/jobs/8980120177#step:2:231

It may because of the issue mentioned in: https://github.com/Project-MONAI/GenerativeModels/issues/386

**Review by KumoLiu — APPROVED** [review]

**Pull request merged**
