### PR TITLE
Update brats_mri_axial_slices_generative_diffusion to monai1.4

### PR DESCRIPTION
**Pull request by Can-Zhao**
Fixes # .

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [x] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [ ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ ] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Review by yiheng-wang-nv — APPROVED** [review]

**Comment by yiheng-wang-nv** [comment]
Hi @Can-Zhao , this PR can merge after https://github.com/Project-MONAI/MONAI/issues/8029 is resolved and having a new monai core tag

**Comment by KumoLiu** [comment]
> Hi @Can-Zhao , this PR can merge after [Project-MONAI/MONAI#8029](https://github.com/Project-MONAI/MONAI/issues/8029) is resolved and having a new monai core tag

1.4.0rc2 tagged: https://pypi.org/project/monai/1.4.0rc2/

**Pull request merged**
