### PR TITLE
Use python3.9 in CI

### LINKED ISSUE #598: Drop python 3.8 in CI
to align with MONAI

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes #598 .

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [ ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ ] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Review by ericspod — APPROVED** [review]
I think this is good, thanks. @KumoLiu may need to trigger blossom here.

**Comment by yiheng-wang-nv** [comment]
blossom tests pass and uses python3.9, I will revert the bundle change and then this PR can merge. cc @KumoLiu

**Review by KumoLiu — APPROVED** [review]

**Pull request merged**
