### PR TITLE
249 add weekly tests

### LINKED ISSUE #249: regular tests for existing models
**Is your feature request related to a problem? Please describe.**
existing bundles will never be tested again once merged into `dev` and deployed.

it would be helpful to test the zipped files regularly by downloading and checking the bundles from here:
https://github.com/Project-MONAI/model-zoo/releases/tag/hosting_storage_v1

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes #249 .

### Description
This PR adds the weekly ci test for existing bundles. It will download all bundles (latest version) from release, and then do the ci test (cpu).

### Status
**Ready**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [ ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ ] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Review by wyli — APPROVED** [review]
looks good to me, btw github action instance has a job time limit of 6 hours, you may want to make each bundle verification an independent job so that each job could run fast and in parallel

**Comment by yiheng-wang-nv** [comment]
> looks good to me, btw github action instance has a job time limit of 6 hours, you may want to make each bundle verification an independent job so that each job could run fast and in parallel

Thanks @wyli ! Do you have any suggestions on how to run separately? I'm not sure since different bundles require different libs (such as different monai, pytorch versions).

**Comment by wyli** [comment]
I think you can use the `matrix` keyword to create parallel jobs https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

also it seems the libraries are installed for each bundle independently https://github.com/Project-MONAI/model-zoo/blob/3bffe793f13a80aa648b559d3f529bb701792ac6/ci/run_regular_tests_cpu.sh#L52-L60
it should be ok to make parallel jobs, or do I miss anything here?

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , could you please help to recheck the updates? I changed to run jobs in parallel. Thanks!

**Pull request merged**
