### PR TITLE
551 Fix premerge py version issue

### LINKED ISSUE #551: Fix premerge cpu test python version issue
already mentioned in https://github.com/Project-MONAI/MONAI/issues/7416
model zoo tests also need to fix this issue

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes #551 

### Description
This PR does the following three changes:
1. fix the python version issue in permerge cpu test
2. update two bundles to support black 24.1
3. update weekly cpu test to enable new bundles tests

### Status
**Ready**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json` if changing an existing bundle.
- [ ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ ] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , @KumoLiu , I had some experiments, I think we can avoid removing `"/opt/hostedtoolcache/Python"` to ensure the python version is what we need for CI test.

related job: https://github.com/Project-MONAI/model-zoo/actions/runs/7676654654/job/20924453064?pr=552#step:7:41

**Review by KumoLiu — APPROVED** [review]

**Comment by yiheng-wang-nv** [comment]
weekly cpu test is checked (https://github.com/Project-MONAI/model-zoo/actions/runs/7690667917)

**Pull request merged**
