### PR TITLE
Fix vista3d bundle evaluation bug

### PR DESCRIPTION
**Pull request by heyufan1995**
Fixes # .

### Description
Fix the evaluation bug.

### CODE REVIEW

**Review by KumoLiu — APPROVED** [review]
Should also update metadata.json
Overall looks good to me, thanks.

**Comment by yiheng-wang-nv** [comment]
I pushed minor changes on readme, and confirmed that the eval config gets metric ~0.96

**Review by yiheng-wang-nv — APPROVED** [review]

**Comment by KumoLiu** [comment]
https://github.com/Project-MONAI/model-zoo/blob/dev/models/vista3d/scripts/evaluator.py#L18
https://github.com/Project-MONAI/model-zoo/blob/dev/models/vista3d/scripts/trainer.py#L19
Here need to be updated to `from monai.utils import IgniteInfo`

**Pull request merged**
