### PR TITLE
Vikash/breastclassification

### PR DESCRIPTION
**Pull request by vikashg**
Fixes # .

### Description
This is a breast density classifier model, that I am working on. I need some help with the train.json file in the config folder. 

### Status
**Work in progress**

### Please ensure all the checkboxes:

- [ ] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [x] Update `version` and `changelog` in `metadata.json`.
- [x] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [x] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [x] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.

### CODE REVIEW

**Comment by vikashg** [comment]
I fixed the loss issue but for someone the `trainer.run()` will not start.

**Comment by Nic-Ma** [comment]
Update: Vikash and I had online discussion about the blocker issues in this bundle, now Vikash continues to develop it.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @vikashg ,

Thanks for your contribution here.
May I know the progress of this PR? Is there any blocker issue?

Thanks in advance.

**Comment by vikashg** [comment]
HI @Nic-Ma, 
I am able to run the code and train everything properly but not using any command line utility. For example if I do this 
```
python -m monai.bundle run trainer --meta_file ./metadata.json --config_file ./train.json
```
I get error regarding the model instantiation 
```

Loading dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:11<00:00,  3.42it/s]
Traceback (most recent call last):
  File "/raid/Vikash/Tools/MONAI-DEPLOY/model-zoo/venv/lib/python3.8/site-packages/monai/utils/module.py", line 218, in instantiate
    return component(**kwargs)
  File "/raid/Vikash/Tools/MONAI-DEPLOY/model-zoo/venv/lib/python3.8/site-packages/monai/utils/deprecate_utils.py", line 202, in _wrapper
    binding = sig.bind(*args, **kwargs).arguments
  File "/usr/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.8/inspect.py", line 3026, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'aux_logits'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/raid/Vikash/Tools/MONAI-DEPLOY/model-zoo/venv/lib/python3.8/site-packages/monai/bundle/config_item.py", line 285, in instantiate
    return instantiate(modname, **args)
  File "/raid/Vikash/Tools/MONAI-DEPLOY/model-zoo/venv/lib/python3.8/site-packages/monai/utils/module.py", line 223, in instantiate
    raise RuntimeError(f"Failed to instantiate '{path}' with kwargs: {kwargs}") from e
RuntimeError: Failed to instantiate 'monai.networks.nets.torchvision_fc.TorchVisionFCModel' with kwargs: {'model_name': 'inception_v3', 'aux_logits': False, 'num_classes': 4, 'in_channels': 2048, 'use_conv': False, 'pool': ''}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

```
This works fine when I call the model using the following method:
```
parser = ConfigParser()
# Read the parser
parser.read_config('../configs/metadata.json')
parser.read_config('../configs/train.json')

#Get the network definition
net = parser.get_parsed_content("network_def")
#Print the network for debugging
print(net)

#Print the train config
trainer = parser.get_parsed_content("trainer")
trainer.run()
```
So, I am trying to reconcile these two things.

**Comment by Nic-Ma** [comment]
Hi @vikashg ,

As the error `TypeError: got an unexpected keyword argument 'aux_logits'`, I think maybe you are using some deprecated arg? Could you please help test it again with the new arg?

Thanks in advance.

**Comment by vikashg** [comment]
Yes I had this problem which is resolved on a PR by adding `aux_logits` as an argument but then Wenqi said `aux_logits` should be handled by **kwargs. 
I will have a look again and push everything. 
Thanks 
Vikash

**Comment by wyli** [comment]
thanks for reporting, maybe it's a bug from the decorator, TorchVisionFCModel https://github.com/Project-MONAI/MONAI/blob/2ed44aa8ed079a0f5b0a5ca2df4044f132de8e54/monai/networks/nets/torchvision_fc.py#L99 
I'll look into it...

**Comment by wyli** [comment]
it's not a bug in `deprecated_utils`, the issue is in the monai version used in this bundle @vikashg, `augx_logits` and inception_v3 models support are only available since this PR https://github.com/Project-MONAI/MONAI/pull/4873, which is developed recently and is not available in monai 0.9.0/0.9.1. they will be available in monai v1.0. Running the

**Comment by vikashg** [comment]
So, @Nic-Ma, what do you suggest should I just ignore the command line driven execution for the current release of the bundle and will patch it after v1.0 is released. What do you think?

Thanks 
Vikash

**Comment by Nic-Ma** [comment]
Hi @vikashg ,

We will release MONAI v1.0.0RC1 today, could you please help update and test again?

Thanks in advance.

**Comment by wyli** [comment]
please try `pip install monai==1.0.0rc1`

**Comment by vikashg** [comment]
ok I will try today. Thanks

**Comment by vikashg** [comment]
So, two things. 
1. When I try to instantiate torchvisionfcmodel with the following arguments. 
```
network = TorchVisionFCModel('inception_v3', num_classes=4,
                             weights='Inception_V3_Weights.IMAGENET1K_V1',
                             use_conv=False, pool=None, aux_logits=False)
print(type(network))
```
It does not take the `aux_logits` as False and produces the following error
```
Traceback (most recent call last):
  File "/raid/Vikash/Tools/MONAI-DEPLOY/model-zoo/models/breast_density_classification/scripts/test_scripts.py", line 14, in <module>
    network = TorchVisionFCModel('inception_v3', num_classes=4,
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/monai/networks/nets/torchvision_fc.py", line 115, in __init__
    model = getattr(models, model_name)(weights=weights, **kwargs)
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/torchvision/models/inception.py", line 463, in inception_v3
    _ovewrite_named_param(kwargs, "aux_logits", True)
  File "/home/gupta/anaconda3/envs/monai-1.0/lib/python3.8/site-packages/torchvision/models/_utils.py", line 238, in _ovewrite_named_param
    raise ValueError(f"The parameter '{param}' expected value {new_value} but got {kwargs[param]} instead.")
ValueError: The parameter 'aux_logits' expected value True but got False instead.
```

The model instantiates with `aux_logits` as `True`. This is not an expected behavior. 

In addition, even if I try to train using the aux_logits as true there is some cuda error, I have an A100 and pytorch 1.12.1 unless monai has some different pytorch requirements. I am looking into this.
```

A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

2022-09-07 10:53:45,893 - Engine run resuming from iteration 0, epoch 0 until 2 epochs
2022-09-07 10:53:46,091 - Current run is terminating due to exception: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by wyli** [comment]
it seems the torchvision model doesn't support weights and aux_logits=False:
```py
>>> from torchvision import models
>>> model = models.inception_v3(weights='Inception_V3_Weights.IMAGENET1K_V1', aux_logits=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/torchvision/models/inception.py", line 463, in inception_v3
    _ovewrite_named_param(kwargs, "aux_logits", True)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/torchvision/models/_utils.py", line 238, in _ovewrite_named_param
    raise ValueError(f"The parameter '{param}' expected value {new_value} but got {kwargs[param]} instead.")
ValueError: The parameter 'aux_logits' expected value True but got False instead.
>>> 
```

**Comment by yiheng-wang-nv** [comment]
Hi @vikashg , do you meet any block issues? Feel free to ask if needed.

**Comment by vikashg** [comment]
Hi @yiheng-wang-nv. There are some issues with how the models are loaded with torchvisionfc. I need to start a new pull request and upload it. I will be able to do that next week as i am at Connectathon in Atlanta for this week. Thabks for checking in

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv. There are some issues with how the models are loaded with torchvisionfc. I need to start a new pull request and upload it. I will be able to do that next week as i am at Connectathon in Atlanta for this week. Thabks for checking in

Sure, feel free to assign me if you need help : )

**Comment by yiheng-wang-nv** [comment]
Hi @vikashg , for this PR, is it fully replaced by the new one? If so, we can close it.

**Comment by vikashg** [comment]
Yes I guess we can close this.

**Comment by vikashg** [comment]
Thanks so much @yiheng-wang-nv @Nic-Ma @wyli for all the help on the other one. I think it will be smoother for the next models. Sorry about that.

**Pull request closed without merging**
