### PR TITLE
spleen_ct_segmentation: remove SaveImage during evaluation

### LINKED ISSUE #90: spleen_ct_segmentation: Evaluation should not save images for FL
**Describe the bug**
Current evaluation file in https://github.com/holgerroth/model-zoo/blob/dev/models/spleen_ct_segmentation/configs/evaluate.json
saves images. 

**To Reproduce**
Run evaluation of bundle

**Expected behavior**
Saving images is not desired in FL were we only want to report back the metric. 

**Screenshots**
n/a

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 0.9.0
Numpy version: 1.23.1
Pytorch version: 1.12.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: af0e0e9f757558d144b655c63afcea3a4e0a06f5
MONAI __file__: /home/hroth/Code2/nvflare/monai-fl/integration/monai/nvflare_monai/lib/python3.8/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 4.0.1
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 9.2.0
Tensorboard version: 2.9.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.64.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.9.1
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.4 LTS
Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.29
Processor: x86_64
Machine: x86_64
Python version: 3.8.10
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 6
Num logical CPUs: 12
Num usable CPUs: 12
CPU usage (%): [16.3, 10.1, 10.0, 29.1, 12.3, 9.9, 10.1, 9.0, 11.1, 10.1, 13.6, 98.8]
CPU freq. (MHz): 1207
Load avg. in last 1, 5, 15 mins (%): [5.8, 7.9, 8.4]
Disk usage (%): 73.9
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 94.0
Available memory (GB): 84.6
Used memory (GB): 8.3

================================
Printing GPU config...
================================
Num GPUs: 2
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70']
GPU 0 Name: NVIDIA TITAN Xp COLLECTORS EDITION
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 30
GPU 0 Total memory (GB): 11.9
GPU 0 CUDA capability (maj.min): 6.1
GPU 1 Name: NVIDIA TITAN Xp COLLECTORS EDITION
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 30
GPU 1 Total memory (GB): 11.9
GPU 1 CUDA capability (maj.min): 6.1
```

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by holgerroth**
Signed-off-by: Holger Roth <hroth@nvidia.com>

Fixes #90.

### Description
remove save image

### Status
**Ready**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [x] In-line docstrings updated.
- [x] Update `version` and `changelog` in `metadata.json`.
- [x] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [x] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [x] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.

### CODE REVIEW

**Comment by wyli** [comment]
Shall we set the disabled flag to true, instead of completely remove the component?

**Comment by yiheng-wang-nv** [comment]
Hi @holgerroth , since the bundle is changed, could you please also modify the `version` and `changelog` in `metadata.json`? Otherwise, the ci test cannot passed. Thanks!

**Comment by holgerroth** [comment]
> Hi @holgerroth , since the bundle is changed, could you please also modify the `version` and `changelog` in `metadata.json`? Otherwise, the ci test cannot passed. Thanks!

Thanks, @yiheng-wang-nv. I updated it.

**Comment by yiheng-wang-nv** [comment]
Met an ssl error (https://github.com/Project-MONAI/model-zoo/runs/7914898236?check_suite_focus=true#step:2:199), it is not related to this PR's changes. I will try to figure out the issue here. cc @wyli @Nic-Ma

**Comment by yiheng-wang-nv** [comment]
> Met an ssl error (https://github.com/Project-MONAI/model-zoo/runs/7914898236?check_suite_focus=true#step:2:199), it is not related to this PR's changes. I will try to figure out the issue here. cc @wyli @Nic-Ma

Hi @holgerroth , according to my test in: https://github.com/Project-MONAI/model-zoo/pull/99, could you please help to modify the `large_files.yml` into [this version](https://github.com/Project-MONAI/model-zoo/blob/4281f08cd4de84f272f7fbe2fb306279410d8f35/models/spleen_ct_segmentation/large_files.yml) ? It can help to avoid the ssl issue. Thanks!

**Comment by holgerroth** [comment]
Thanks @yiheng-wang-nv , I updated large_files.yml

**Review by yiheng-wang-nv — APPROVED** [review]

**Pull request merged**
