### PR TITLE
Add model.ts to torchscript

### PR DESCRIPTION
**Pull request by kbressem**
### Description
As discussed in #102 I uploaded the `TorchScript` model and updated `large_files.yaml`

### Status
**Ready

### Please ensure all the checkboxes:
**no code changes**

### CODE REVIEW

**Comment by Nic-Ma** [comment]
Hi @kbressem ,

As the CI error shows:
```
ValueError: version number: 0.1.0 is already used of bundle: prostate_mri_anatomy. Please change it.
```
You are changing the bundle content, please upgrade the `version number` and `changelog` in the `metadata.json`.

Thanks in advance.

**Review by Nic-Ma — APPROVED** [review]

**Comment by kbressem** [comment]
Hi @Nic-Ma 
The `metadata.json` has been updated. 
Thank you for merging

**Pull request merged**
