### PR TITLE
98 Fix ssl issue

### LINKED ISSUE #98: SSL error in premerge ci test
https://github.com/Project-MONAI/model-zoo/runs/7914898236?check_suite_focus=true#step:2:199

### PR DESCRIPTION
**Pull request by yiheng-wang-nv**
Fixes #98 .

### Description
A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [ ] In-line docstrings updated.
- [ ] Update `version` and `changelog` in `metadata.json`.
- [ ] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ ] Descriptions should be consistent with the content, such as `eval_metrics` of the provided weights and TorchScript modules.
- [ ] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.

### CODE REVIEW

**Review by Nic-Ma — APPROVED** [review]

**Comment by Nic-Ma** [comment]
I think you also fixed issue https://github.com/Project-MONAI/model-zoo/issues/90 in this PR.
Please mark it in your description.

Thanks.

**Comment by yiheng-wang-nv** [comment]
> I think you also fixed issue #90 in this PR. Please mark it in your description.
> 
> Thanks.

Thanks @Nic-Ma , I will remove the changes of spleen bundle (here just for debug) after resolving the issue.

**Comment by yiheng-wang-nv** [comment]
download large files from: renalStructures_UNEST_segmentation bundle works, see: [153c1fb](https://github.com/Project-MONAI/model-zoo/pull/99/commits/153c1fb155dbf7f7022eb5d8ba0b5ccebd1374d0)

**Comment by yiheng-wang-nv** [comment]
I did multiple experiments to locate the root cause but cannot find why only spleen bundle's download link has the ssl certificate issue on blossom ci (works fine in local machine and ngc, also works fine for other bundles), thus I make a new copy of those large files and replace the link, and it passes now (see: https://github.com/Project-MONAI/model-zoo/pull/99/commits/4281f08cd4de84f272f7fbe2fb306279410d8f35). Therefore, I will close this ticket so far.

**Pull request closed without merging**
