### PR TITLE
Corrected image size from 229 to 299 in metadata.json

### PR DESCRIPTION
**Pull request by vikashg**
Fixes # .

### Description
Resolving issue #303 

### Status
**Ready*

### Please ensure all the checkboxes:

- [x] Codeformat tests passed locally by running `./runtests.sh --codeformat`.
- [x ] In-line docstrings updated.
- [x ] Please ensure the naming rules in config files meet our requirements (please refer to: `CONTRIBUTING.md`).
- [x] Ensure versions of packages such as `monai`, `pytorch` and `numpy` are correct in `metadata.json`.
- [ x] Files larger than 25MB are excluded and replaced by providing download links in `large_file.yml`.
- [ x] Avoid using path that contains personal information within config files (such as use `/home/your_name/` for `"bundle_root"`).

### CODE REVIEW

**Comment by yiheng-wang-nv** [comment]
Hi @vikashg , thanks for the updates. Could also address the following issue:

There are two "Input and Output Formats" sections in README, and one of them may be an outdated version and should be removed. In addition, could you please also mention what is the input size when you do training? It can help users to avoid size related debug.

**Comment by vikashg** [comment]
> Hi @vikashg , thanks for the updates. Could also address the following issue:
> 
> There are two "Input and Output Formats" sections in README, and one of them may be an outdated version and should be removed. In addition, could you please also mention what is the input size when you do training? It can help users to avoid size related debug.

Thanks @yiheng-wang-nv Sorry about that. Fixed it.

**Review by yiheng-wang-nv — APPROVED** [review]
Thanks @vikashg !

**Pull request merged**
